### ISSUE TITLE
Spring Boot 3.0 support?

### ISSUE THREAD

**Issue by odrotbohm** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#2]
It looks like the binaries built from the 2.7.x branch do not work on Boot 3.0 snapshots as they refer to API removed. Will there be an updated version compatible with 3.0 at some point?

**Comment by michaelmosmann** [comment]
@odrotbohm i think so .. i hope that it will be not as hard..

**Comment by michaelmosmann** [comment]
@odrotbohm btw: i did not remove an API, the used some accessible code in an unintended way and after a longer discussion they decided that the will remove the support in 2.7 ...

This has also some benefits.. there is a major refactoring ahead and this can not be done in any way without code change on the spring side:)

**Comment by Heatmanofurioso** [comment]
Any idea on when/how will this be worked on?

Or anyone has an idea on a workaround with 3.0.0?

**Comment by michaelmosmann** [comment]
@Heatmanofurioso i will start with this today.. maybe this is something easy .. 
any NOT working sample project?

**Comment by Heatmanofurioso** [comment]
@michaelmosmann I've made a sample repo.
This code was working fine with `2.7.0`

https://github.com/Heatmanofurioso/sample-spring-mongo-repo

**Comment by michaelmosmann** [comment]
@Heatmanofurioso cool.. thanks.. :)

**Comment by michaelmosmann** [comment]
@Heatmanofurioso .. have something working. Had fun with something like this:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files
.. i do not get it why there was no warning in spring 2.7 ..

**Comment by michaelmosmann** [comment]
@Heatmanofurioso made an pull request: https://github.com/Heatmanofurioso/sample-spring-mongo-repo/pull/1

**Comment by michaelmosmann** [comment]
@Heatmanofurioso spring 3.0 release done:) reopen if needed..

**Comment by Heatmanofurioso** [comment]
Thanks for your help @michaelmosmann 
I've tested on several of my repos, and it's working perfectly
