### ISSUE TITLE
Change path fastdl-mongodb

### ISSUE THREAD

**Issue by ShimonMimoun** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#24]
Hello everyone,

I'm using Java 17 and Spring 3. I would like to change the download path for the MongoDB version to a different link.

Let me explain my issue. I am working in an environment where access to the external server is limited.

Previously, I used this solution, but it no longer works. 

   @Bean
    public DownloadConfigBuilderCustomizer downloadCustomizer() {
        DistributionDownloadPath downloadPath = new SameDownloadPathForEveryDistribution(DOWNLOAD_PATH);
        return downloadConfigBuilder -> {
            downloadConfigBuilder.downloadPath(downloadPath);
            downloadConfigBuilder.userAgent(USER_AGENT);
        };
    }

Do you have any ideas on how to proceed?

**Comment by michaelmosmann** [comment]
@ShimonMimoun You can change the server for the download to a local one: 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md#customize-download-url

.. but as you are using spring you may apply this customization this way:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/HowTo.md#customize-mongod

**Comment by michaelmosmann** [comment]
@ShimonMimoun there are more ways to customize this.. but this is maybe the easiest one.. i think i should add some documentation for this kind of problem ...

**Comment by ShimonMimoun** [comment]
How can I go about it then? I would greatly appreciate your guidance and any potential solutions.

Thank you for your response!

**Comment by ShimonMimoun** [comment]
@michaelmosmann 

Thank you for your response. I have already tried that, but it still tries to connect to the main Atlas server. Can you guide me on how to do this? I tried modifying the mongod builder, but I wasn't successful. Could you please enlighten me on how to accomplish this?

**Comment by michaelmosmann** [comment]
@ShimonMimoun can you show me some code?

**Comment by ShimonMimoun** [comment]
```
    @Bean
    public Mongod mongoConfiguration() {
        return Mongod.builder()
                .distributionBaseUrl(Start.to(DistributionBaseUrl.class)
                        .initializedWith(DistributionBaseUrl.of(DOWNLOAD_PATH)))
                .build();
    }
```
    or
    
```
    @Bean
    public MongoClient mongoConfiguration(){
        return MongoClients.create(
                new MongoClientOptions.Builder()
                        .setDownloadUrl(DOWNLOAD_PATH)
                        .build());
    }
```

**Comment by ShimonMimoun** [comment]
I have found the solution, and I'm sharing it with you.

    @Bean
    BeanPostProcessor customizeMongod() {
        return TypedBeanPostProcessor.applyBeforeInitialization(Mongod.class, src ->
                Mongod.builder()
                        .from(src)
                        .distributionBaseUrl(
                                Start.to(DistributionBaseUrl.class)
                                        .initializedWith(DistributionBaseUrl.of(DOWNLOAD_PATH))
                        )
                        .build());
    }


Thanks for your help @michaelmosmann
