### ISSUE TITLE
Cannot set version via IFeatureAwareVersion bean

### ISSUE THREAD

**Issue by chillb0nes** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#27]
Hello! I'm developing a custom boot starter for my team which configures some common dev dependencies. I want to set embedded mongodb version in this boot starter auto-configuration, so that the `de.flapdoodle.mongodb.embedded.version` property does not have to be set in every project that uses it.

I tried to define version bean as follows:
```java
@Bean
public IFeatureAwareVersion embeddedMongoVersion() {
    return Version.V4_4_16;
}
```
but I still got an error: `java.lang.IllegalStateException: Set the de.flapdoodle.mongodb.embedded.version property or define your own IFeatureAwareVersion bean to use embedded MongoDB`.

I think the IFeatureAwareVersion bean in your auto-configuration 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/0fda9e0e9cea0099089134d25a4dc698c4104615/src/main/java/de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration.java#L119-L122
is missing `@ConditionalOnMissingBean` annotation, so it can't be overridden.

**Comment by michaelmosmann** [comment]
@chillb0nes ah..ok.. i think i can change that.

**Comment by michaelmosmann** [comment]
@chillb0nes .. I do welcome every contribution:)

**Comment by chillb0nes** [comment]
Looks like this was already fixed with https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/commit/7f25beec41cdf3f0323de90caf0a8e3f750bc1ae. I checked original case with newer version, and it works now.

**Comment by michaelmosmann** [comment]
@chillb0nes .. i think i forgot that i fixed that already.. sorry.. :)
