### ISSUE TITLE
Embedded Mongo Still running when there is an exception

### ISSUE THREAD

**Issue by rajakumare1** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#28]
If there is any exception in the data setup in @BeforeEach, we are seeing the mongd is still running in the background
If this populateMockTestCollection() method has an exception, the mongod is running without gracefully shutdown

`@ExtendWith(SpringExtension.class)
@ActiveProfiles("test")
@SpringBootTest(
        properties = "de.flapdoodle.mongodb.embedded.version=5.0.12"
)
@Import({TestMongoConfiguration.class})
@AutoConfigureDataMongo()
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext
class ServiceIntegrationTest {
    

    @Autowired
    private TestCollectionRepository testCollectionRepository;

    @BeforeEach
    void setup() throws IOException {
TestCollection testcollection = populateMockTestCollection(); // If this populateMockTestCollection has an exception, the mongod is running without shutdown
 testCollectionRepository.insert(testcollection);
    }

......

}
@TestConfiguration

public class TestMongoConfiguration {

    @Bean
    public MongoDatabaseFactory mongoDbFactory() throws Exception {
        return new SimpleMongoClientDatabaseFactory("mongodb://localhost:27017/db-tests");
    }

    @Bean
    MongoTemplate mongoTemplate(MongoDatabaseFactory factory) {
        return new MongoTemplate(factory);
    }

}
`

**Comment by michaelmosmann** [comment]
@rajakumare1 .. hmm.. spring should handle this case.. but i will have a look into that.. maybe something is missing

**Comment by michaelmosmann** [comment]
Should be solved with newer versions of this library..
