### ISSUE TITLE
import a json file containing mongo documents into Embedded DB in Spring

### ISSUE THREAD

**Issue by rajakumare1** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#29]
I have 100's of documents stored inside sample.json and I want to load it in spring project Junit while starting the embeded mongodb. using the below reference , how should I do it. Please advise?

Note: I referred the import section in  https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/embed-mongo-4.x/Howto.md. But i didnt understand how I can integrate it with Spring support.

 I have multiple collections with multiple records. Tats why I am looking for this support that will help  rather than inserting each record for every Junit. Thanks!!!

`@ExtendWith(SpringExtension.class)
@activeprofiles("test")
@SpringBootTest(
properties = "de.flapdoodle.mongodb.embedded.version=5.0.12"
)
@Import({TestMongoConfiguration.class})
@AutoConfigureDataMongo()
@testinstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext
class ServiceIntegrationTest {

@Autowired
private TestCollectionRepository testCollectionRepository;

@BeforeEach
void setup() throws IOException {
TestCollection testcollection = populateMockTestCollection(); 
testCollectionRepository.insert(testcollection);
}

......

}
@TestConfiguration

public class TestMongoConfiguration {

@Bean
public MongoDatabaseFactory mongoDbFactory() throws Exception {
    return new SimpleMongoClientDatabaseFactory("mongodb://localhost:27017/db-tests");
}

@Bean
MongoTemplate mongoTemplate(MongoDatabaseFactory factory) {
    return new MongoTemplate(factory);
}
}
`

**Comment by michaelmosmann** [comment]
@rajakumare1 i will improve the documentation on that .. because it is not that easy .. 

you need to customize your mongodb-starter: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/HowTo.md#customize-mongod
where you trigger only an import: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/embed-mongo-4.x/Howto.md#import-json-file-with-mongoimport-command ... 

but you should wait for a working sample for that.. (maybe today)

**Comment by rajakumare1** [comment]
@michaelmosmann Any luck with the sample. Thanks!!

**Comment by michaelmosmann** [comment]
@rajakumare1 not finished yet.. was in a hurry.. stay tuned.. sorry

**Comment by nithin-mk** [comment]
Hello @michaelmosmann , I have a Spring Boot project with auto-configured Embedded MongoDB. I've entered spring.data.mongodb.port=20017, spring.data.mongodb.database=mydb and de.flapdoodle.embedmongo.version=6.0.3 and it automatically starts the mongod process in a test and I can query all repositories. My question is how to run the mongoimport process without starting an additional mongod server at a random port at the beginning of each test? The documentation in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md#import-json-file-with-mongoimport-command starts an additional mongod server at a random port, with which mongoimport connects, whereas my auto-wired MongoTemplate connects to port 20017.

**Comment by michaelmosmann** [comment]
@nithin-mk can you create an extra issue for that.. i have an idea how to solve this..

**Comment by nithin-mk** [comment]
Thanks @michaelmosmann! I've created the issue: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/issues/63
