### ISSUE TITLE
Spring Transaction with mongodb not working 

### ISSUE THREAD

**Issue by haiderali22** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#3]
I was working on  a sample to test transaction with mongodb and spring boot and as per the docs i have also provided the MongoTransactionManager bean  and set the replica property but still not working as expected 

GitHub repo link https://github.com/haiderali22/mongodb-transaction-test

**Comment by michaelmosmann** [comment]
@haiderali22 i will have a look at this.. (later this day) thanks for the repo:)

**Comment by haiderali22** [comment]
you can run TestTransaction(addTransactionalTest) to verify this

**Comment by michaelmosmann** [comment]
@haiderali22 .. hmm.. did not had the time yesterday.. will do today.

**Comment by michaelmosmann** [comment]
@haiderali22 .. first finding:
you should not mix spring and flapdoodle property prefix .. spring will win.. if you change it to either spring or flapdoodle:
--
de.flapdoodle.mongodb.embedded.storage.replSetName=testing
de.flapdoodle.mongodb.embedded.storage.oplogSize=10
de.flapdoodle.mongodb.embedded.version=5.0.5
---
.. then mongodb will not start as he states that replSetName does not work with --nojournal

**Comment by michaelmosmann** [comment]
@haiderali22 .. and it looks like that you may need more then just a replica set name to make it work (https://www.baeldung.com/spring-data-mongodb-transactions) .. i will try to create a working solution for this, but it is a little bit more complicated...

**Comment by michaelmosmann** [comment]
@haiderali22 ok.. it looks like you need a working replica set to make this work: https://stackoverflow.com/questions/50255195/how-to-configure-a-mongodb-cluster-which-supports-sessions

**Comment by haiderali22** [comment]
I tested the code by creating a docker container with following docker compose file

version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-transaction
    hostname: mongodb
    restart: on-failure
    environment:
      - MONGO_INITDB_DATABASE=demo
    ports:
      - 27017:27017
    healthcheck:
      test: mongo --eval "rs.initiate()"
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --replSet rs0"


The transaction part is working fine, i was using this library to see if i can write test cases with embeded database

**Comment by michaelmosmann** [comment]
Ah.. thanks.. I think rs.initiate() is important.. I will see if I can make this work.

**Comment by michaelmosmann** [comment]
@haiderali22 .. yes.. rs.initiate() did the trick..will make a new release and will tests this with your example:) .. in the next days..

**Comment by michaelmosmann** [comment]
@haiderali22 i made an pull request with a working solution.. 
as you see i am using the new beta-version of this framework .. as this kind of change is hard in the legacy code base.. i will fine tune this a little bit, improve the documentation and will make beta to the new release version.. 

Can you try if this solves your problem? there are very subtle tweaks.. f.i. you can not create the service instance yourself as spring has no way to intercept the method call..

**Comment by haiderali22** [comment]
@michaelmosmann thankyou working fine with suggested changes

**Comment by michaelmosmann** [comment]
@haiderali22 .. did a cleanup.. now even less changes needed:)

**Comment by michaelmosmann** [comment]
@haiderali22 .. close it it works for you:)
