### ISSUE TITLE
I  am  upgrading  springbot 2.x to  springboot3.2 some java  file is not found  in latest de.flapdoodle.embed 4.8 jar  

### ISSUE THREAD

**Issue by usingh20** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#32]
Below java  file is not found  in latest de.flapdoodle.embed jar  
 de.flapdoodle.embed.process.config.RuntimeConfig;
 de.flapdoodle.embed.process.config.store.SameDownloadPathForEveryDistribution;
 de.flapdoodle.embed.process.extract.UserTempNaming;
 de.flapdoodle.embed.process.io.directories.FixedPath;
 de.flapdoodle.embed.mongo.Command;
 de.flapdoodle.embed.mongo.MongodExecutable;
 de.flapdoodle.embed.mongo.config.Defaults;
 de.flapdoodle.embed.mongo.config.MongodConfig;

**Comment by michaelmosmann** [comment]
@usingh20 from which spring version did you upgrade? Do you use this spring integration?

**Comment by usingh20** [comment]
@michaelmosmann  I am upgrading  from springboot 2.7.6 to  springboot 3.2  and Spring 5.3 

![image](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/assets/67550345/942f3f50-d81c-4e15-afab-96566905fee4)

**Comment by michaelmosmann** [comment]
@usingh20 do you have some own code using de.flapdoodle code? If you are using spring 2.7.x out of the box the spring integration provided by spring itself did use a much older version of my library.

**Comment by michaelmosmann** [comment]
@usingh20  i will close this issue.. reopen if needed.
