### ISSUE TITLE
Unable to run it on Azure Linux

### ISSUE THREAD

**Issue by edilson** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#36]
Hi, I'm trying to run this lib inside the github codespaces which uses Azure Linux but I'm receiving a similar error described on #34. What kind of workaround I could use in order to make it run?

**Comment by michaelmosmann** [comment]
@edilson can you set some kind of system properties? than you may switch from os detection to a fixed one: https://github.com/flapdoodle-oss/de.flapdoodle.os#run

**Comment by michaelmosmann** [comment]
@edilson i close this issue.. reopen if needed.
