### ISSUE TITLE
Custom Mongod().builder() cannot find executable path provided for Downloaded ZIP

### ISSUE THREAD

**Issue by Mojojomo** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#38]
Hi @michaelmosmann 

I am writing integration tests for an application. Attempting to use embedded mongo 5.0.13

I have the ZIP file downloaded from the company's artificatory and I am trying to point to this ZIP file to be used instead of having it downloaded at run time

`Mongod.builder().build()
.withExtractPackage(Start.to(ExtractedFileSet.class)
.initializedWith(ExtaxtedFileSet.builder(srcPath). executable (exePath).build()))`

Paths I am providing:
srcPath=/embeddedMongo/mongodb-x86_64-5.0.13
exePath=/embeddedMongo/mongodb-x86_64-5.0.13/bin/

Getting Exception
`java.lang.IllegalArgumentException: executable at /embeddedMongo/mongodb-x86_64-5.0.13/bin does not exist`

Could you let me know what path I should provide to executable.

I have also tried placing extracting the zip to {user.home}/.embedmongo/win32 but Spring is still attempting to download the ZIP which is not the desired result.

**Comment by michaelmosmann** [comment]
@Mojojomo is there a change that you can use the latest version of this library?

**Comment by Mojojomo** [comment]
> @Mojojomo is there a change that you can use the latest version of this library?
@michaelmosmann 
Not sure I follow your question.. I am making use of 
de.flapdoodle.embed.mongo.spring31x:4.9.3
And mongo 5.0.13

**Comment by michaelmosmann** [comment]
@Mojojomo .. oh sorry. Was on a wrong track.. you can not just provide an zip file .. its a little bit more complicated. As this use case has no documentation yet, i would like to understand it as good as possible. Some background:

There is some code which tries to detect the current operating system.. then some code which gives the path to the matching artifact based on the mongodb server version. With this path and the server name the downloader tries do download this archive and put it in an directory with the hash of the url (same url, same directory,..). Then the exceutable is extracted from the archive and put in an other directory where the hash of the archive is part of the path (same content of the archive, same directory). So if you want to shortcut this process you have to change all of that.. which is possible, but somehow complicated.

Maybe it is easier to change only some of that.. you could put the needed artifacts on your own server and only change the server name (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md#customize-download-url). AFAIK file-urls are supported too.. you need to put the downloaded artifact into the right path and it should work without changing any other part.

If this is not possible or not desired it would be nice if you could explain it a little bit:)

**Comment by Mojojomo** [comment]
@michaelmosmann I could try changing the server to download from the company's repo, but I will need to provide credentials for it...
Could you provide a sample of how that would work, have not seen examples where credentials are provided.

**Comment by michaelmosmann** [comment]
@Mojojomo i will see if i can create an matching example..

**Comment by michaelmosmann** [comment]
@Mojojomo should work with the next release: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#customize-download-url

**Comment by michaelmosmann** [comment]
@Mojojomo i will close this issue.., reopen if needed.
