### ISSUE TITLE
Disable embedded mongo on specific Sping boot profiles

### ISSUE THREAD

**Issue by mmuruev** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#42]
Is this any way to specify in which test profile embedded mongo should be used? Will be nice have respect to spring boot profiles with way to setup it in config files like embedded.disabled=true

**Comment by michaelmosmann** [comment]
@mmuruev as i am not using spring myself i do not know if this may help: https://stackoverflow.com/a/55403963 and then exclude EmbeddedMongoAutoConfiguration.class this way.

**Comment by michaelmosmann** [comment]
@mmuruev  i close this issue, reopen if needed..
