### ISSUE TITLE
FileAlreadyExists for .embedmongo/fileSets/hashes/xxxx

### ISSUE THREAD

**Issue by K0nstantine** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#48]
We use embed.mongo.spring for tests and they fail randomly in Tekton-Tasks with the following Exception:

> Caused by: java.nio.file.FileAlreadyExistsException: /root/.embedmongo/fileSets/hashes/ebb0bb5b11aeca90f1437d5ae0db2dc4508488c9c63ac5f11072ee82923f3162
>   	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
>   	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
>   	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
>   	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
>   	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
>   	at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
>   	at java.base/java.nio.file.Files.write(Files.java:3492)
>   	at de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore.lambda$readOrCreateArchiveContentAndFileSetDescriptionHash$9(ContentHashExtractedFileSetStore.java:162)
>   	at de.flapdoodle.types.ThrowingRunnable.lambda$mapException$0(ThrowingRunnable.java:28)
>  	... 134 more

We have 2 TestsClasses that are using embed.mongo. They look like this:

```
@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DirtiesContext
class EventsConsumptionTest extends AbstractKafkaTest {
    @Autowired
    private Repository repo;
    @Autowired
    private ObjectMapper objectMapper;

    @BeforeAll
    public void setUp() {
        setUpProducer();
    }

    @AfterEach
    public void reset() {
        repo.deleteAll();
    }

    @Test
    @SneakyThrows
    void testCreatedEvent() {
        Created event = this.objectMapper.readValue(new File(EVENTS_PATH + "/created.json"), Created.class);
        sendEvent(inboundTopic, event);
        Thread.sleep(2000);
        Optional<Entity> saved = repo.findById(event.getId());
        assertFalse(saved.isEmpty());
    }
```
We also have defined MongoConfiguration for the tests:
```
@Configuration
public class MongoTestConfig {

    @Bean
    MongodArguments mongodArguments() {
        return MongodArguments.builder()
            .replication(Storage.of("test", 10))
            .build();
    }
}
```
Tests work locally with no problems. In the Build-Pipeline fails nearly every 5th build. If you could help on this one, it would be great!

**Comment by michaelmosmann** [comment]
@K0nstantine .. hmm.. i have to look into this..

**Comment by K0nstantine** [comment]
Hier noch der Exception-Stack dazu:
[exception_stack.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/files/14838434/exception_stack.txt)

**Comment by michaelmosmann** [comment]
@K0nstantine  .. ah.. danke:) ich hab so eine Idee...

**Comment by michaelmosmann** [comment]
@K0nstantine .. habs gefunden. release folgt.

**Comment by michaelmosmann** [comment]
@K0nstantine .. release 4.12.3, sollte in den nächsten Stunden in maven central sein
.. ich schließe das mal, einfach wieder aufmachen, wenn nötig.

**Comment by michaelmosmann** [comment]
@K0nstantine ... are there more than one jvm (ci build agent?) running on this machine at the same time?

**Comment by K0nstantine** [comment]
One Container is started per build. Which means it has to be only one JVM for this particular build.

**Comment by michaelmosmann** [comment]
@K0nstantine .. hmm. Do you have a recent stack trace for that?

**Comment by K0nstantine** [comment]
[exception_stack.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/files/14884271/exception_stack.txt)

One more update: error happens only with multiple test files, which load Spring Context (@SpringBootTest). With a single test - no error happens.

**Comment by michaelmosmann** [comment]
@K0nstantine did a new release (4.12.4) .. i think i fixed that:) did only a new release for this project

**Comment by K0nstantine** [comment]
Works like a charm! Could you explain what the error was or did you just update some third-party dependencies?
Vielen lieben dank auf jedem Fall!
