### ISSUE TITLE
No support for Ubuntu 23.10 with de.flapdoodle.embed.mongo.spring27x

### ISSUE THREAD

**Issue by druion** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#49]
**Issue**
Appears to be the same issue as seen under the artifactId de.flapdoodle.embed.mongo described here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/460

After upgrading from Ubuntu 22.10 (which was working fine) to Ubuntu 23.10 I now have the issue where it tries to fallback to Ubuntu 20.04 which should work but also fails.
  
**Error**
```shell
  (os=Linux)
    fallback to Ubuntu_20_04
```

**Failing Setup** 
pom.xml
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.7.18</version>
<dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-mongodb</artifactId>
    <version>2.7.18</version>
</dependency>

<dependency>
    <groupId>de.flapdoodle.embed</groupId>
    <artifactId>de.flapdoodle.embed.mongo.spring27x</artifactId>
    <version>4.12.6</version>
    <scope>test</scope>
</dependency>
```

application.yml
```
spring:
  mongodb:
    embedded:
      version: 4.4.17
``` 

**Workaround**
I am able to get the integration test running with the following override argument. Could the issue be resolved so this is not needed?
```
mvn clean verify -D"de.flapdoodle.os.override=Linux|X86_64|Ubuntu|Ubuntu_22_10"
``` 

Many Thanks for your support.

**Comment by michaelmosmann** [comment]
@druion i will have a look...

**Comment by michaelmosmann** [comment]
@druion .. you you have a more complete stack trace of your problem?

**Comment by michaelmosmann** [comment]
@druion i close this issue.. reopen if needed.
