### ISSUE TITLE
could not resolve package for genericfeatureawareversion{6.3.1}:platform{operatingsystem=linux, architecture=x86_64, distribution=debian, version=debian_9}

### ISSUE THREAD

**Issue by KrisDaCoder** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#60]
Hi

I'am not able to resolve package for Debian testing.

**Comment by michaelmosmann** [comment]
@KrisDaCoder i guess you need at least Debian 10 for something >5.x.x ..

**Comment by KrisDaCoder** [comment]
@michaelmosmann yep. I'm gonna close this as irrelevant considering that Debian 9 is also EOL.
