### ISSUE TITLE
Run mongoimport with auto-configured running mongod

### ISSUE THREAD

**Issue by nithin-mk** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#63]
I have a Spring Boot project with auto-configured Embedded MongoDB. I've entered spring.data.mongodb.port=20017, spring.data.mongodb.database=mydb and de.flapdoodle.embedmongo.version=6.0.3 and it automatically starts the mongod process in a test and I can query all repositories. My question is how to run the mongoimport process without starting an additional mongod server at a random port at the beginning of each test? The documentation in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md#import-json-file-with-mongoimport-command starts an additional mongod server at a random port, with which mongoimport connects, whereas my auto-wired MongoTemplate and repositories connect to port 20017.

**Comment by nithin-mk** [comment]
Hello, will this be part of the upcoming release? :)

**Comment by nithin-mk** [comment]
@michaelmosmann Thank you for fixing this! The new release and example are working for me.

It's beyond the scope of this ticket, but would it be possible to run mongosh instead of mongoimport as well? As mongosh supports a broader set of functionality. I use MongoDB 6 and I can see that mongosh is not supported in this issue: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/524

**Comment by nithin-mk** [comment]
One such use case for mongosh would be to initialize with custom user and role.

**Comment by michaelmosmann** [comment]
@nithin-mk i had some trouble to make mongosh work again.. but maybe i give it a new try..
