### ISSUE TITLE
MongoDB v8 support

### ISSUE THREAD

**Issue by infoShare** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#64]
Is there any timeline for MongoDB v8 support here ? 
Embedded Mongo itself is supporting it since 4.17.0.

**Comment by michaelmosmann** [comment]
@infoShare .. i hope i can make a release today with v8 support.

**Comment by michaelmosmann** [comment]
@infoShare release done.. :)

**Comment by infoShare** [comment]
Thank you very much !

**Comment by michaelmosmann** [comment]
@infoShare hmm.. AFAIK the latest version for redhat7 is (this file is generated: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/test/resources/de/flapdoodle/embed/mongo/packageresolver/explainedSnapshot.txt) 7.3.3-rc0 or 7.0.14 .. you can try to override os detection (https://github.com/flapdoodle-oss/de.flapdoodle.os?tab=readme-ov-file#run) maybe the redhat8 version does run on redhat7.
